DROP TABLE IF EXISTS Etudiant;
CREATE TABLE Etudiant (
Numero INTEGER PRIMARY KEY AUTOINCREMENT,
DateCreation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Code TEXT NOT NULL,
Nom TEXT NOT NULL,
Prenom TEXT NOT NULL,
Adresse TEXT NOT NULL
);
